# Loading Data

In [6]:
import sys
import os

sys.path.append(os.path.abspath(os.path.join('..')))

from src.data.loader import load_raw_data

#Load the data into a DataFrame variable
df_not_clean = load_raw_data()

df_not_clean.head()

Successfully located and loaded raw data from: data/raw/agent_tool_tasks.csv

,task_uid,is_live_benchmark,task_complexity,task_domain,query,tool_names,query_word_count,num_available_tools,total_params,total_required_params,...,query_multi_intent_score,query_specificity_score,query_unique_token_ratio,query_code_signal,query_temporal_signal,query_sensitive_data_signal,param_type_diversity,structured_param_ratio,schema_rigidity_score,can_answer
0,task_00001,1,low,other,air,ThinQ_Connect,1,1,1,1,...,0,0.0,1.000000,0,0,0,1,1.00,0.7500,0
1,task_00002,1,low,travel,what is your name?,get_current_weather,4,1,2,1,...,0,0.0,1.000000,0,0,0,1,0.00,0.4000,0
2,task_00003,1,low,travel,Could you give me Python code that get 2 int t...,get_current_weather,14,1,2,1,...,1,1.5,1.000000,1,0,0,1,0.00,0.4000,0
3,task_00004,0,high,other,Find me the most recent art sculpture by James...,get_zodiac_compatibility|local_nursery.find|ge...,13,4,10,7,...,0,0.5,1.000000,0,0,0,4,0.10,0.4100,1
4,task_00005,0,medium,other,"""Can you help me find a recipe that uses chick...",restaurant.find|recipe.find,58,2,4,3,...,7,5.5,0.627119,0,1,0,3,0.25,0.6125,1

# Adding Mandatory Features

In [8]:
import pandas as pd
import sys

sys.path.append('../')
import src.features.mandatory as mandatory

df = mandatory.fill_missing_text(df_not_clean)

df_Mfeatures = mandatory.build_mandatory_features(df)

columns_to_check = [
    'query', 'query_avg_word_length', 
    'tool_names', 'tool_name_diversity', 
    'avg_params_per_tool','required_params_ratio',
    'query_mentions_number'
]
display(df_Mfeatures[columns_to_check].head())

,query,query_avg_word_length,tool_names,tool_name_diversity,avg_params_per_tool,required_params_ratio,query_mentions_number
0,air,0.0,ThinQ_Connect,1,1.0,1.00,0
1,what is your name?,0.0,get_current_weather,1,2.0,0.50,0
2,Could you give me Python code that get 2 int t...,0.0,get_current_weather,1,2.0,0.50,0
3,Find me the most recent art sculpture by James...,0.0,get_zodiac_compatibility|local_nursery.find|ge...,4,2.5,0.70,0
4,"""Can you help me find a recipe that uses chick...",0.0,restaurant.find|recipe.find,2,2.0,0.75,0